Fix/hooked problems
Amsterdam-Music-Lab/MUSCLE pull request #1021
Opened 2024-05-21 15:51 UTC by BeritJanssen

Close #1018, close #762 (again).

2024-05-25 06:41 UTC, Evert-R commented
The issues in this PR are solved but now when running matching pairs or categorization the questionaire isn't shown and the experiment freezes. No error message just an empty screen.

![no-questions](https://github.com/Amsterdam-Music-Lab/MUSCLE/assets/49793452/50ed9cf7-1883-4d04-8f32-769dee3f869a)

2024-05-25 06:42 UTC, Evert-R requested changes
The issues in this PR are solved but now when running matching pairs or categorization the questionaire isn't shown and the experiment freezes. No error message just an empty screen.

![no-questions](https://github.com/Amsterdam-Music-Lab/MUSCLE/assets/49793452/8c5ffac9-f415-48ae-b119-cc93cc7d126e)

2024-05-27 07:37 UTC, BeritJanssen commented
Ah, thanks for catching that! Removing the `await` message seemed to be without side effects for the experiments I tested, but I guess it's the culprit for breaking MatchingPairs and Categorization.

2024-05-27 07:44 UTC, BeritJanssen commented on frontend/src/components/Trial/Trial.jsx
> +    const [preloadReady, setPreloadReady] = useState(false);
It's actually this part which is problematic, as we don't have a `setPreloadReady` command in Trials without Playback.

2024-05-27 07:55 UTC, merged