CI: Refactor e2e tests and add smoke tests for production environment"
Amsterdam-Music-Lab/MUSCLE pull request #1143
Opened 2024-06-21 07:57 UTC by drikusroor

This PR adds simple short-lived smoke tests that we can use to do a sanity check after a deploy to production. Furthermore, it refactors the e2e suite as a whole by splitting up the *actual* e2e tests from the smoke tests so that we can execute them separately if needed. Both the e2e tests and the smoke tests rely on the same base and execution command, but one can filter which one(s) to run using the parameters `--smoke` and `--e2e`. Omitting the parameters executes both smoke and e2e tests.

Resolves #1060

2024-06-22 06:47 UTC, albertas-jn approved these changes

2024-06-25 07:11 UTC, BeritJanssen commented on e2e/tests/smoke/test_google.py
Is there a way to test internet connection without relying on elgoog?

2024-06-25 07:14 UTC, BeritJanssen requested changes
A teensy and somewhat nitpicky request: most of the committed files don't have an empty last line. While my editor isn't bothered by that, some editors are. That's why GitHub also flags this. Please configure your editor to add an empty last line, so future collaborators/maintainers don't curse over our graves. ;-)

2024-06-25 08:05 UTC, drikusroor commented
> A teensy and somewhat nitpicky request: most of the committed files don't have an empty last line. While my editor isn't bothered by that, some editors are. That's why GitHub also flags this. Please configure your editor to add an empty last line, so future collaborators/maintainers don't curse over our graves. ;-)

This is kind of new to me. If we want empty last lines in every file, shouldn't we have an (opinionated) settings file for VS Code at least?

2024-06-25 08:07 UTC, drikusroor commented on e2e/tests/smoke/test_google.py
Maybe, but why would we not use google? It's probably the service in the world with the most up-time.

2024-06-25 12:00 UTC, BeritJanssen commented on e2e/tests/smoke/test_google.py
I thought there might be a non-corporate alternative. But yes, for the foreseeable future, Google probably has the most reliable up-time.

2024-06-25 12:01 UTC, BeritJanssen commented
We have an `.editorconfig` which should take care of that. That has `insert_final_newline = true`, as a matter of fact.

2024-06-27 13:10 UTC, drikusroor commented on e2e/tests/smoke/test_google.py
I've added Cloudflare to the mix just in case

2024-06-27 13:11 UTC, drikusroor commented
> We have an `.editorconfig` which should take care of that. That has `insert_final_newline = true`, as a matter of fact.

Ah I see.. VS Code does need a plugin to be able to work with that. Maybe it would be an idea to add it to the "Recommended plugins" in the `.vscode` folder or would that be overkill?

2024-06-27 13:22 UTC, merged