Feature er/duplicate experiment
Amsterdam-Music-Lab/MUSCLE pull request #1330
Opened 2024-10-29 08:05 UTC by Evert-R

This PR adds a `duplicate` inline action to the experiments on the admin overview.

Clicking on duplicate will first show an input to enter an extention for the slugs.
This input will be stripped from non alphanumeric characters, and added  to all the slugs, seperated by an hyphen.
(so entering `copy` will add `-copy` to all the slugs.

New objects will be created for:
- Experiment
- phases
- blocks
- experiment translated content
- block translated content

These objects will be reassigned:
- playlists
- theme_config
- image

closes: #1136

2024-10-29 08:25 UTC, BeritJanssen commented on backend/experiment/admin.py
> +            slug_extention = request.POST.get("slug-extention")
```suggestion
            slug_extension = request.POST.get("slug-extension")
```

2024-10-29 08:28 UTC, BeritJanssen commented on backend/experiment/templates/duplicate-experiment.html
> +    <label for="slug-extention">Enter an extention to add to the slugs in the dupicated experiment:</label>
```suggestion
    <label for="slug-extension">Enter an extension to add to the slugs in the duplicated experiment:</label>
```

2024-10-29 08:50 UTC, BeritJanssen requested changes
Nice! I had envisioned the duplication to be formless, i.e., you would just click duplicate and get a copy of the experiment, with all slugs getting a `-copy` attached automatically, and it would then be up to the user to change the slug afterwards. It's also nice to let admin users set the extension right away though, so I'm not opposed to this solution for sure.

What I like about the form is that it explains so well what exactly the duplication is going to do. If we want to not use the form, this could be moved (in shortened form) to a help text shown when hovering over the "duplicate" button, perhaps.

One thing I do think this PR needs to still tackle is to check for duplicate slugs before attempting to save the object: if a there's already an `Experiment` or `Block` object with `slug-copy`, we couldn't save another object with `slug-copy` because of the unique constraint. This would throw an error. So then we might still need to attach integers to the slug (`slug-copy1`), and then also check that the integer that's attached hasn't yet been used... This is a nice one for test-driven development.

2024-10-29 09:36 UTC, Evert-R commented
> Nice! I had envisioned the duplication to be formless, i.e., you would just click duplicate and get a copy of the experiment, with all slugs getting a `-copy` attached automatically, and it would then be up to the user to change the slug afterwards. It's also nice to let admin users set the extension right away though, so I'm not opposed to this solution for sure.
> 
> What I like about the form is that it explains so well what exactly the duplication is going to do. If we want to not use the form, this could be moved (in shortened form) to a help text shown when hovering over the "duplicate" button, perhaps.

My reasoning was that it prevents accidental clicks on the `duplicate` button, which would duplicate an entire experiment. (Most functions in the admin have a confirm screen) 
The other reason is that you would almost always want to change the `-copy` extension to something else. With multiple blocks this could be a drag. 

> One thing I do think this PR needs to still tackle is to check for duplicate slugs before attempting to save the object: if a there's already an `Experiment` or `Block` object with `slug-copy`, we couldn't save another object with `slug-copy` because of the unique constraint. This would throw an error. So then we might still need to attach integers to the slug (`slug-copy1`), and then also check that the integer that's attached hasn't yet been used... This is a nice one for test-driven development.

Good point ! I now also noticed that you can have multiple experiments with the same slug, as the `unique` argument is not set on the `Experiment` model, like it's set on the `Block` model.
I will look into this as well.

2024-10-29 10:31 UTC, BeritJanssen commented
Good point, I agree that it's better to have the form.

We should add the `unique` constraint on the `Experiment.slug`, good that you checked!

2024-10-29 10:35 UTC, BeritJanssen commented
BTW, instead of auto-modifying slugs, we might of course also consider returning a validation error on the form: "This slug extension is already taken. Please choose another one."

I also wonder whether we couldn't also reuse the slug validation from Django and throw a validation error to the user, rather than tacitly adjusting anything that isn't an allowed for a `SlugField`. A bit more annoying to users, but then they know why the cannot use "f***Extension!!" or something similar.

2024-11-05 07:44 UTC, BeritJanssen approved these changes

2024-11-12 12:43 UTC, BeritJanssen approved these changes

2024-11-12 12:50 UTC, merged