Feature/optional header
Amsterdam-Music-Lab/MUSCLE pull request #989
Opened 2024-05-02 08:03 UTC by BeritJanssen

Close #941 by adding a configurable header to the theme. I didn't manage to get the unit tests working (something about needing to embed the `DefaultPage` render in a `<(Browser)Router>`, but doing that gave another error message), so I stubbed them for now. NB: revert 76e1863b2b7bac18e7e06265e9d072555ad226ad to continue working on them, I had some boilerplate already in place before that commit. But in the interest of delivering this in time, will defer this until later. We need comparable tests for #980, so then this can hopefully be picked up.

2024-05-02 12:38 UTC, drikusroor requested changes
I'm a bit concerned about both the `ThemeConfig` and the `DefaultPage` being somewhere in between something generic and something `Experiment(Collection)` oriented, though I'm not sure what the solution should be. Secondly, I feel like the frontend hasn't been finished properly: The experiment tiles seem to be vertically stacked and the other theme properties haven't been implemented. As for the latter, I think you could just copy + paste the font loader & background image configuration from the Experiment or perhaps even use this opportunity to abstract the font loader & background image to one single page/layout.

2024-05-05 09:19 UTC, BeritJanssen commented on backend/experiment/serializers.py
> +        'theme_id': experiment_collection.theme_config.pk if experiment_collection.theme_config else None
I did this based on earlier feedback in which you seemed to be concerned about mixing different models in one serialization.

2024-05-05 09:21 UTC, BeritJanssen commented on backend/theme/serializers.py
> +    }
Indeed, with #928 as a proposed course of action, I think the link of `Experiment` to `ThemeConfig` can be removed eventually.

2024-05-05 09:21 UTC, BeritJanssen commented on frontend/src/components/Page/DefaultPage.jsx
> +const DefaultPage = ({ className, title, logoClickConfirm, collectionSlug='', nextExperimentSlug='', children }) => {
Perhaps I should indeed make a new component.

2024-05-05 09:22 UTC, BeritJanssen commented on frontend/src/components/Page/DefaultPage.jsx
> +    const theme = useBoundStore((state) => state.theme);
This should indeed still be adjusted.

2024-05-21 15:40 UTC, merged